---
title: "Data Analysis: Antibiotic treatment influences cnidarian regeneration rate"
author: "JK"
date: "2024-08-19"
output: html_document
---
```{r}
library(emmeans)
library(ggplot2)
library(dplyr)
library(broom)
library(car)
library(performance)
library(scales)
library(plotrix)
library(multcomp)
library(gridExtra)
library(ggplot2)
library(ellipse)
library(factoextra)
library(vegan)
library(ARTool)
library(MCMC.OTU)
library(ggpubr)
library(ggsignif)
library(ggpubr)
library(survival)   # If using survival curves
library(cmprsk)     # If dealing with competing risks
library(RColorBrewer)
#install.packages("ggpubr")
library(MASS)
library(stargazer)

```


```{r}

setwd("~/Desktop/Regeneration_2024")
# Load the data
data<-read.csv("Regeneration_data.csv", header = TRUE)

#Assign colors and shapes
#colors for treatment
colvec<- c("Control" = "#4292c6", "Antibiotic" = "coral1")
#Brown: CE8451
#Pink: D65278
#Green:307253
#Gray:9FA6A9
#green "#556B2F"
#colors for baseline apo and sym
shapes = c("VWB" = 21, "CC7" = 22, "H2"= 24, "NC"=23, "ME"=21)

str(data)

```

```{r}

data$Treatment <- factor(data$Treatment, levels = c("Control","Antibiotic"))
data$Organism <- factor(data$Organism, levels = c("Nematostella","Aiptasia"))
# Visualize the data distribution
ggplot(data.frame(data), aes(x = data$Tentacle_length.mm.)) + 
  geom_histogram(binwidth = 1, fill="pink") + 
  theme_minimal() 
#data skewed to the left. needs normalization
# square root Transformation 
data$Tentacle_length.mm._sq <- sqrt(data$Tentacle_length.mm.)
shapiro_test_log <- shapiro.test(data$Tentacle_length.mm._sq)
print(shapiro_test_log)
#W = 0.97845, p-value = 0.07938

ggplot(data.frame(data), aes(x = data$Tentacle_length.mm._sq)) + 
  geom_histogram(binwidth = 1, fill="pink") + 
  theme_minimal() 
#data is now normally distributed

reg<-ggplot(data,(aes(x=Treatment ,y=Tentacle_length.mm.,fill=Treatment,group=Treatment, shape=Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.5,outlier.shape = NA)+
  geom_point(position = position_jitterdodge(jitter.width = 0.9, dodge.width = 0.95), size = 2.5, alpha = 0.8)+
 # geom_jitter(size=2.9,width = 0.20, alpha=0.8,height = 0)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("Tentacle length (mm)")+ theme(legend.position = "none")+facet_wrap(~Organism)
reg
ggsave("~/Desktop/Regeneration_2024/Regeneration_tentacle0824.pdf",reg, width =3.5, height = 2.5)
reg
```


```{r}
#both data were non normally distributed. squate root transformation is necessary. 
stella=filter(data, Organism == "Nematostella")
#normalize and conduct statistical test
str(stella)
shapiro.test(stella$Tentacle_length.mm.)
#no of the trransformation worked.

stella$Treatment <- as.factor(stella$Treatment)
stella$Strain <- as.factor(stella$Strain)
# Apply ART
#ART (NON Parametric) allows for the analysis of interaction effects and main effects in data that are not normally distributed or have unequal variances
st_art <- art(Tentacle_length.mm.~ Treatment * Strain, data = stella)
# Perform ANOVA on ART results
anova(st_art)
```
```{r}
# Compute mean and SE for each combination of Treatment and Strain
stella_tent_table <- stella %>%
  group_by(Treatment) %>%
  summarise(
    Mean = mean(Tentacle_length.mm., na.rm = TRUE),
    SE = sd(Tentacle_length.mm., na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(stella_tent_table)
```



```{r}
#filter aiptasia data only
aiptasia=filter(data, Organism == "Aiptasia")
shapiro.test(aiptasia$Tentacle_length.mm._sq)
#no of the trransformation worked.

aiptasia$Treatment <- as.factor(aiptasia$Treatment)
aiptasia$Strain <- as.factor(aiptasia$Strain)
# Apply ART
ai_art <- art(Tentacle_length.mm.~ Treatment * Strain, data = aiptasia)
# Perform ANOVA on ART results
anova(ai_art)
```


```{r}
# Compute mean and SE for each combination of Treatment and Strain
ai_tent_table <- aiptasia %>%
  group_by(Treatment) %>%
  summarise(
    Mean = mean(Tentacle_length.mm., na.rm = TRUE),
    SE = sd(Tentacle_length.mm., na.rm = TRUE) / sqrt(n())
  )

# View the summary table
print(ai_tent_table)
```

```{r}
data <- read.csv("Regen_rate_aip_v2.csv.csv")

# Subset data for Nematostella and Aiptasia separately
stella<- subset(data, Organism == "Nematostella")
aiptasia <- subset(data, Organism == "Aiptasia")

# Cox model for Nematostella
cox_nematostella <- coxph(Surv(Day, Regenerating) ~ Treatment * Strain, data = stella)
summary(cox_nematostella)
```


```{r}
# Cox model for Aiptasia
cox_aiptasia <- coxph(Surv(Day, Regenerating) ~ Treatment * Strain, data = aiptasia)
summary(cox_aiptasia)
```


```{r}
Day <- stella$Day
Regenerating <-stella$Regenerating
# This creates a new factor variable where each level is a combination of Treatment and Strain
Treatment <- interaction(stella$Treatment, stella$Strain)

library(cmprsk)
#KM or CI plots are useful to see the uptake or increase in abundance alongside time.
fit.CIF <- cuminc(ftime=Day,fstatus=Regenerating,group=Treatment,cencode=0)
fit.CIF
plot(fit.CIF, fun = function(x) 1 - x, ylab = "Regeneration_aip", xlab = "Days",
     lwd = 3, lty = c(2, 2, 1, 1), col = c("coral1", "skyblue1", "coral1","skyblue1"))
 
Day <- aiptasia$Day
Regenerating <-aiptasia$Regenerating
# This creates a new factor variable where each level is a combination of Treatment and Strain
Treatment <- interaction(aiptasia$Treatment, aiptasia$Strain)

library(cmprsk)
#KM or CI plots are useful to see the uptake or increase in abundance alongside time.
fit.CIF <- cuminc(ftime=Day,fstatus=Regenerating,group=Treatment,cencode=0)
fit.CIF
plot(fit.CIF, fun = function(x) 1 - x, ylab = "Regeneration_aip", xlab = "Days",
     lwd = 3, lty = c(2, 2, 1, 1), col = c("coral1", "skyblue1", "coral1","skyblue1"))

#pdf("~/Desktop/Regeneration_2024/Regeneration_st.pdf", width = 3.5, height = 4.5)
# Basic plot to check without the 'type' argument
#plot(fit.CIF, fun = function(x) 1 - x, ylab = "Regeneration_aip", xlab = "Days",
#     lwd = 3, lty = c(2, 2, 1, 1), col = c("coral1", "skyblue1", "coral1","skyblue1"))
#dev.off() 

#pdf("~/Desktop/Regeneration_2024/Regeneration_ai.pdf", width = 3.5, height = 4.5)
#plot(fit.CIF, fun = function(x) 1 - x, ylab = "Regeneration_aip", xlab = "Days",
#     lwd = 3, lty = c(2, 2, 1, 1), col = c("coral1", "skyblue1", "coral1","skyblue1"))
#dev.off() 

```


```{r}
#do analysis for tentacle number
# Load the data
tent<-read.csv("Tentacle_number.csv", header = TRUE)

#Assign colors and shapes
#colors for treatment
colvec<- c("Control" = "#4292c6", "Antibiotic" = "coral1")
#Brown: CE8451
#Pink: D65278
#Green:307253
#Gray:9FA6A9
#green "#556B2F"
#colors for baseline apo and sym
shapes = c("CC7" = 22, "H2"= 24, "NC"=23, "ME"=21)

str(tent)

tent$Treatment <- factor(tent$Treatment, levels = c("Control","Antibiotic"))
tent$Strain<-as.factor(tent$Strain)
tent$Organism<-factor(tent$Organism, levels = c("Nematostella", "Aiptasia"))
# Visualize the data distribution
ggplot(data.frame(tent), aes(x = tent$Tentacle.Count.Average)) + 
  geom_histogram(binwidth = 1, fill="pink") + 
  theme_minimal() 
#data seems normal

#check normality
shapiro.test(sqrt(tent$Tentacle.Count.Average))
shapiro_tent <- shapiro.test(tent$Tentacle.Count.Average)
print(shapiro_tent)
#data:  tent$Tentacle.Count.Average
#W = 0.94967, p-value = 0.003552. Non normal. needs transformation
# square root Transformation 
shapiro.test(sqrt(tent$Tentacle.Count.Average))


tent_plot<-ggplot(tent,(aes(x=Treatment ,y=Tentacle.Count.Average,fill=Treatment,group=Treatment, shape=Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.5,outlier.shape = NA)+
  geom_point(position = position_jitterdodge(jitter.width = 0.9, dodge.width = 0.95), size = 2.5, alpha = 0.8)+
 # geom_jitter(size=2.9,width = 0.20, alpha=0.8,height = 0)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("Number of Tentacles")+ theme(legend.position = "none")+facet_wrap(~Organism)
ggsave("~/Desktop/Regeneration_2024/Regeneration_tentNum0824.pdf",tent_plot, width =3.5, height = 2.5)

tent_plot

```

```{r}
stella_tnt=filter(tent, Organism == "Nematostella")
#normalize and conduct statistical test
str(stella_tnt)
#cube root transform
tent_cube<-stella_tnt$Tentacle.Count.Average^(1/3)
check_normality(tent_cube)
#W = 0.57057, p-value = 1.268e-09 didnt work
shapiro.test(sqrt(stella_tnt$Tentacle.Count.Average))
#sqrt didnt work

# Apply ART
st_tent <- art(Tentacle.Count.Average~ Treatment * Strain, data = stella_tnt)
# Perform ANOVA on ART results
anova(st_tent)
```
```{r}
# Compute tentatecle num mean and SE for each combination of Treatment and Strain
stella_num_table <- stella_tnt %>%
  group_by(Treatment) %>%
  summarise(
    Mean = mean(Tentacle.Count.Average, na.rm = TRUE),
    SE = sd(Tentacle.Count.Average, na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(stella_num_table)
```

```{r}
#filter aiptasia data only
aipt_tent=filter(tent, Organism == "Aiptasia")
# Apply ART
ai_tent <- art(Tentacle.Count.Average~ Treatment * Strain, data = aipt_tent)
# Perform ANOVA on ART results
anova(ai_tent)
```
```{r}
# Compute tentatecle num mean and SE for each combination of Treatment and Strain
aip_num_table <- aipt_tent %>%
  group_by(Treatment) %>%
  summarise(
    Mean = mean(Tentacle.Count.Average, na.rm = TRUE),
    SE = sd(Tentacle.Count.Average, na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(aip_num_table)
```

```{r}
cfu<-read.csv("CFU_counts_regeneration.csv", header = TRUE)

#Assign colors and shapes
#colors for treatment
colvec<- c("Control" = "#4292c6", "Antibiotic" = "coral1")
#Brown: CE8451
#Pink: D65278
#Green:307253
#Gray:9FA6A9
#green "#556B2F"
#colors for baseline apo and sym
shapes = c("CC7" = 22, "H2"= 24, "NC"=23, "ME"=21)

str(cfu)

# Calculate CFU per mL
cfu$CFU_per_mL <- (cfu$Colony_count * cfu$Dilution) / cfu$total_plated
str(cfu)
cfu$Treatment <- factor(cfu$Treatment, levels = c("Control","Antibiotic"))
cfu$Organism <- factor(cfu$Organism, levels = c("Nematostella","Aiptasia"))
# Ensure Treatment is a factor and check levels
cfu$Treatment <- as.factor(cfu$Treatment)
levels(cfu$Treatment)

# Ensure Strain is a factor if you are using it in shapes
cfu$Strain <- as.factor(cfu$Strain)
levels(cfu$Strain)

ggplot(cfu,(aes(x=Treatment ,y=CFU_per_mL,fill=Treatment,group=Treatment, shape = Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.2,outlier.shape = NA)+
  geom_jitter(size=2.9,width = 0.20, alpha=0.8)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("CFU/Animal")+ theme(legend.position = "left")+facet_wrap(~Organism,scales = "free_y")

cfu_plot<-ggplot(cfu,(aes(x=Treatment ,y=CFU_per_mL,fill=Treatment,group=Treatment, shape=Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.5,outlier.shape = NA)+
  geom_point(position = position_jitterdodge(jitter.width = 0.9, dodge.width = 0.95), size = 2.5, alpha = 0.8)+
 # geom_jitter(size=2.9,width = 0.20, alpha=0.8,height = 0)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("CFU/Individual")+ theme(legend.position = "none")+facet_wrap(~Organism,scales = "free_y")
ggsave("~/Desktop/Regeneration_2024/Regeneration_CFU.pdf",cfu_plot, width =4, height = 2.5)
cfu_plot
```


```{r}
#filter stella
#filter stella data
st_cfu=filter(cfu, Organism == "Nematostella")
ai_cfu=filter(cfu, Organism == "Aiptasia")

ste_stat <- aov(CFU_per_mL ~ Treatment*Strain, data=st_cfu)
summary(ste_stat)
check_normality(ste_stat)
shapiro.test(sqrt(st_cfu$CFU_per_mL))
#didnt work
shapiro.test(log(st_cfu$CFU_per_mL+0.001))
#didnt work
shapiro.test(log(st_cfu$CFU_per_mL+1))
#didnt work

# Apply ART
st_cfu_st <- art(CFU_per_mL~ Treatment * Strain, data = st_cfu)
# Perform ANOVA on ART results
anova(st_cfu_st)
```
```{r}
# Compute tentatecle num mean and SE for each combination of Treatment and Strain
st_cfu_table <- st_cfu %>%
  group_by(Treatment,Strain) %>%
  summarise(
    Mean = mean(CFU_per_mL, na.rm = TRUE),
    SE = sd(CFU_per_mL, na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(st_cfu_table)
```


```{r}
# Apply ART
ai_cfu_st <- art(CFU_per_mL~ Treatment * Strain, data = ai_cfu)
# Perform ANOVA on ART results
anova(ai_cfu_st)
```
```{r}
# Compute tentatecle num mean and SE for each combination of Treatment and Strain
ai_cfu_table <- ai_cfu %>%
  group_by(Treatment,Strain) %>%
  summarise(
    Mean = mean(CFU_per_mL, na.rm = TRUE),
    SE = sd(CFU_per_mL, na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(ai_cfu_table)
```

```{r}
asex<-read.csv("Asexual_reproduction.csv", header = TRUE)
str(asex)
asex$Treatment <- factor(asex$Treatment, levels = c("Control","Antibiotic"))
asex$Strain<-as.factor(asex$Strain)
ggplot(asex,(aes(x=Treatment ,y=Number_Clones,fill=Treatment,group=Treatment, shape = Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.2,outlier.shape = NA)+
  geom_jitter(size=2.9,width = 0.20, alpha=0.8)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("Asexual reproduction 
  (no. of clones produced)")+ theme(legend.position = "left")


asex_ai<-ggplot(asex,(aes(x=Treatment ,y=Number_Clones,fill=Treatment,group=Treatment, shape=Strain)))+ 
  geom_boxplot(lwd=1.25,alpha = 0.5,outlier.shape = NA)+
  geom_point(position = position_jitterdodge(jitter.width = 0.9, dodge.width = 0.95), size = 2.5, alpha = 0.8)+
 # geom_jitter(size=2.9,width = 0.20, alpha=0.8,height = 0)+
  scale_fill_manual(values=colvec)+scale_color_manual(values=colvec)+
  theme_classic()+ scale_shape_manual(values = shapes)+
  theme_classic()+ ylab("Asexual reproduction 
  (no. of clones produced)")+ theme(legend.position = "none")
ggsave("~/Desktop/Regeneration_2024/Regeneration_Asex.pdf",asex_ai, width =2, height = 2.5)
asex_ai

```


```{r}
shapiro.test(asex$Number_Clones)
asex_st <- aov(Number_Clones ~ Treatment*Strain, data=asex)
summary(asex_st)
check_normality(asex_st)

# Apply ART
ai_cfu_as <- art(Number_Clones ~ Treatment*Strain, data=asex)
# Perform ANOVA on ART results
anova(ai_cfu_as)

```
```{r}
# Compute tentatecle num mean and SE for each combination of Treatment and Strain
as_cfu_table <- asex %>%
  group_by(Treatment) %>%
  summarise(
    Mean = mean(Number_Clones, na.rm = TRUE),
    SE = sd(Number_Clones, na.rm = TRUE) / sqrt(n())
  )
# View the summary table
print(as_cfu_table)
```



